SELECT
    TRUNC(SYSDATE,'HH24') - 1/24 AS DATES,
    COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) AS SHIPNODE_KEY,
    CASE WHEN COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) IS NULL THEN NULL ELSE RR.DELIVERY_METHOD END AS DELIVERY_METHOD,
    (CASE WHEN COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) IN ('859','869','879','889') THEN 'LFC'
       ELSE N.NODE_TYPE END) AS NODE_TYPE,
    (CASE WHEN RR.DELIVERY_METHOD = 'PICK' THEN 'BPS'
       WHEN
         RR.DELIVERY_METHOD = 'SHP' AND RR.CARRIER_SERVICE_CODE = 'Same Day' THEN 'SDD'
       WHEN
         RR.DELIVERY_METHOD = 'SHP' AND RR.CARRIER_SERVICE_CODE IS NULL AND N.NODE_TYPE = 'STORE' THEN 'SFS'
       WHEN
         COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) IS NULL THEN 'SYSTEMS/OTHER'
       ELSE
         'DELIVERY' END) AS FULFILLMENT_TYPE,
    RR.ECOMM_ORDER_CNT AS ECOMM_ORD_CNT,
    COUNT(DISTINCT RR.ORDER_HEADER_KEY) AS NW_DMND_ORD_CNT,
    SUM(RR.ORIGINAL_ORDERED_QTY) AS NW_DMND_UNT_CNT,
    SUM(RR.LINE_TOTAL) AS NW_DMND_SLS_AMT,
    ROUND(SUM (RR.LINE_TOTAL)/ COUNT(DISTINCT RR.ORDER_HEADER_KEY),2) AS AOV,
    ROUND(SUM (RR.LINE_TOTAL)/ SUM(RR.ORIGINAL_ORDERED_QTY),2) AS AUR
FROM
    (SELECT
        HH.ORDER_HEADER_KEY,
        HH.ORDER_LINE_KEY,
        HH.ORIGINAL_ORDERED_QTY,
        HH.LINE_TOTAL,
        HH.SHIPNODE_KEY,
        HH.DELIVERY_METHOD,
        HH.ECOMM_ORDER_CNT,
        MIN(HH.CARRIER_SERVICE_CODE) AS CARRIER_SERVICE_CODE,
        MIN(R.ORDER_RELEASE_KEY) AS ORDER_RELEASE_KEY
    FROM
      (SELECT
           H.ORDER_HEADER_KEY,
           L.ORDER_LINE_KEY,
           L.ORIGINAL_ORDERED_QTY,
           COALESCE(DSV.LINE_TOTAL,L.LINE_TOTAL) AS LINE_TOTAL,
           COALESCE(DSV.SHIPNODE_KEY,L.SHIPNODE_KEY) AS SHIPNODE_KEY,
           L.DELIVERY_METHOD,
           (CASE WHEN L.CARRIER_SERVICE_CODE = 'Same Day' THEN 'Same Day' ELSE NULL END) AS CARRIER_SERVICE_CODE,
           COUNT(DISTINCT H.ORDER_HEADER_KEY) OVER () AS ECOMM_ORDER_CNT
        FROM
         STERLING.YFS_ORDER_HEADER H
         INNER JOIN STERLING.YFS_ORDER_LINE L
           ON
            H.ORDER_HEADER_KEY = L.ORDER_HEADER_KEY AND H.DOCUMENT_TYPE = '0001'
           LEFT OUTER JOIN
             (SELECT
                L1.ORDER_HEADER_KEY,
                L1.ORDER_LINE_KEY,
                L.ORIGINAL_ORDERED_QTY,
                L1.LINE_TOTAL,
                L.SHIPNODE_KEY
              FROM STERLING.YFS_ORDER_HEADER H
               INNER JOIN
                   STERLING.YFS_ORDER_LINE L
               ON
               H.ORDER_HEADER_KEY = L.ORDER_HEADER_KEY
               AND
               H.DOCUMENT_TYPE = '0005'
               INNER JOIN
                  STERLING.YFS_ORDER_LINE L1
               ON
               L.CHAINED_FROM_ORDER_LINE_KEY = L1.ORDER_LINE_KEY
               WHERE
                 H.ORDER_DATE >= (
                   CASE WHEN
                         TO_CHAR(TRUNC(SYSDATE,'HH24'),'HH24') = '00' THEN TRUNC(SYSDATE) -1
                        ELSE
                         TRUNC(SYSDATE)
                       END)
               AND H.ORDER_DATE < TRUNC(SYSDATE,'HH24')
               )DSV
           ON
             DSV.ORDER_HEADER_KEY = L.ORDER_HEADER_KEY
             AND
             DSV.ORDER_LINE_KEY = L.ORDER_LINE_KEY
           WHERE
             H.ORDER_DATE >= (
               CASE
                WHEN
                  TO_CHAR(TRUNC(SYSDATE,'HH24'),'HH24') = '00'
                THEN
                  TRUNC(SYSDATE) -1
           ELSE TRUNC(SYSDATE)
             END)
           AND H.ORDER_DATE < TRUNC(SYSDATE,'HH24')
       ) HH
    LEFT OUTER JOIN
      STERLING.YFS_ORDER_RELEASE R
    ON
     R.ORDER_HEADER_KEY = HH.ORDER_HEADER_KEY
    GROUP BY
     HH.ORDER_HEADER_KEY,
     HH.ORDER_LINE_KEY,
     HH.ORIGINAL_ORDERED_QTY,
     HH.LINE_TOTAL,
     HH.SHIPNODE_KEY,
     HH.DELIVERY_METHOD,
     HH.ECOMM_ORDER_CNT) RR
LEFT OUTER JOIN STERLING.YFS_ORDER_RELEASE R1
ON
 RR.ORDER_RELEASE_KEY = R1.ORDER_RELEASE_KEY
LEFT OUTER JOIN
  STERLING.YFS_SHIP_NODE N
ON
  COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) = N.SHIPNODE_KEY
GROUP BY
 COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY),
 CASE
   WHEN
     COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) IS NULL THEN NULL ELSE RR.DELIVERY_METHOD END,
     RR.ECOMM_ORDER_CNT,
 (CASE
   WHEN
     COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) IN ('859','869','879','889') THEN 'LFC'
     ELSE
       N.NODE_TYPE
     END),
 (CASE WHEN RR.DELIVERY_METHOD = 'PICK' THEN 'BPS'
       WHEN RR.DELIVERY_METHOD = 'SHP' AND RR.CARRIER_SERVICE_CODE = 'Same Day' THEN 'SDD'
       WHEN RR.DELIVERY_METHOD = 'SHP' AND RR.CARRIER_SERVICE_CODE IS NULL AND N.NODE_TYPE = 'STORE' THEN 'SFS'
       WHEN COALESCE(RR.SHIPNODE_KEY,R1.SHIPNODE_KEY) IS NULL THEN 'SYSTEMS/OTHER'
       ELSE 'DELIVERY' END)